begin transaction;

DROP TABLE IF EXISTS Project_Author CASCADE;
DROP TABLE IF EXISTS Project_Production CASCADE;
DROP TABLE IF EXISTS Project CASCADE;
DROP TABLE IF EXISTS Production_Author CASCADE;
DROP TABLE IF EXISTS Production CASCADE;
DROP TABLE IF EXISTS Activity_ProfessionalExperience CASCADE;
DROP TABLE IF EXISTS Activity CASCADE;
DROP TABLE IF EXISTS ProfessionalExperience CASCADE;
DROP TABLE IF EXISTS Supervisor CASCADE;
DROP TABLE IF EXISTS Thesis CASCADE;
DROP TABLE IF EXISTS Education CASCADE;
DROP TABLE IF EXISTS Distinction CASCADE;
DROP TABLE IF EXISTS Address CASCADE;
DROP TABLE IF EXISTS Phone CASCADE;
DROP TABLE IF EXISTS Email CASCADE;
DROP TABLE IF EXISTS Website CASCADE;
DROP TABLE IF EXISTS Identifier CASCADE;
DROP TABLE IF EXISTS Language CASCADE;
DROP TABLE IF EXISTS CV CASCADE;
DROP TABLE IF EXISTS Author CASCADE;
drop table if exists UserToken cascade;
DROP TABLE IF EXISTS Users CASCADE;

DROP TYPE IF EXISTS language_level CASCADE;
DROP TYPE IF EXISTS identifier_type CASCADE;
DROP TYPE IF EXISTS education_degree CASCADE;
DROP TYPE IF EXISTS education_status CASCADE;
DROP TYPE IF EXISTS supervisor_role CASCADE;
DROP TYPE IF EXISTS funding_type CASCADE;
DROP TYPE IF EXISTS project_state CASCADE;
DROP TYPE IF EXISTS distinction_type CASCADE;
DROP TYPE IF EXISTS contact_type CASCADE;
DROP TYPE IF EXISTS phone_device CASCADE;
DROP TYPE IF EXISTS website_type CASCADE;

end transaction;