/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActivityDTO
 */
export interface ActivityDTO {
    /**
     * 
     * @type {number}
     * @memberof ActivityDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ActivityDTO
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ActivityDTO
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof ActivityDTO
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof ActivityDTO
     */
    endDate?: Date;
}

/**
 * Check if a given object implements the ActivityDTO interface.
 */
export function instanceOfActivityDTO(value: object): value is ActivityDTO {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    return true;
}

export function ActivityDTOFromJSON(json: any): ActivityDTO {
    return ActivityDTOFromJSONTyped(json, false);
}

export function ActivityDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivityDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'],
        'description': json['description'] == null ? undefined : json['description'],
        'startDate': (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
    };
}

export function ActivityDTOToJSON(json: any): ActivityDTO {
    return ActivityDTOToJSONTyped(json, false);
}

export function ActivityDTOToJSONTyped(value?: ActivityDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'description': value['description'],
        'startDate': ((value['startDate']).toISOString().substring(0,10)),
        'endDate': value['endDate'] == null ? undefined : ((value['endDate']).toISOString().substring(0,10)),
    };
}

