/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailDTO
 */
export interface EmailDTO {
    /**
     * 
     * @type {number}
     * @memberof EmailDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof EmailDTO
     */
    type: EmailDTOTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof EmailDTO
     */
    address: string;
}


/**
 * @export
 */
export const EmailDTOTypeEnum = {
    Personal: 'Personal',
    Professional: 'Professional'
} as const;
export type EmailDTOTypeEnum = typeof EmailDTOTypeEnum[keyof typeof EmailDTOTypeEnum];


/**
 * Check if a given object implements the EmailDTO interface.
 */
export function instanceOfEmailDTO(value: object): value is EmailDTO {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    return true;
}

export function EmailDTOFromJSON(json: any): EmailDTO {
    return EmailDTOFromJSONTyped(json, false);
}

export function EmailDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'],
        'address': json['address'],
    };
}

export function EmailDTOToJSON(json: any): EmailDTO {
    return EmailDTOToJSONTyped(json, false);
}

export function EmailDTOToJSONTyped(value?: EmailDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'address': value['address'],
    };
}

