/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImportCvRequest
 */
export interface ImportCvRequest {
    /**
     * 
     * @type {Blob}
     * @memberof ImportCvRequest
     */
    file: Blob;
}

/**
 * Check if a given object implements the ImportCvRequest interface.
 */
export function instanceOfImportCvRequest(value: object): value is ImportCvRequest {
    if (!('file' in value) || value['file'] === undefined) return false;
    return true;
}

export function ImportCvRequestFromJSON(json: any): ImportCvRequest {
    return ImportCvRequestFromJSONTyped(json, false);
}

export function ImportCvRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportCvRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'file': json['file'],
    };
}

export function ImportCvRequestToJSON(json: any): ImportCvRequest {
    return ImportCvRequestToJSONTyped(json, false);
}

export function ImportCvRequestToJSONTyped(value?: ImportCvRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file': value['file'],
    };
}

