/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActivityDTO } from './ActivityDTO';
import {
    ActivityDTOFromJSON,
    ActivityDTOFromJSONTyped,
    ActivityDTOToJSON,
    ActivityDTOToJSONTyped,
} from './ActivityDTO';

/**
 * 
 * @export
 * @interface ProfessionalExperienceDTO
 */
export interface ProfessionalExperienceDTO {
    /**
     * 
     * @type {number}
     * @memberof ProfessionalExperienceDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ProfessionalExperienceDTO
     */
    institution: string;
    /**
     * 
     * @type {string}
     * @memberof ProfessionalExperienceDTO
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof ProfessionalExperienceDTO
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProfessionalExperienceDTO
     */
    endDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof ProfessionalExperienceDTO
     */
    type: ProfessionalExperienceDTOTypeEnum;
    /**
     * 
     * @type {Array<ActivityDTO>}
     * @memberof ProfessionalExperienceDTO
     */
    activities?: Array<ActivityDTO>;
}


/**
 * @export
 */
export const ProfessionalExperienceDTOTypeEnum = {
    Science: 'Science',
    TeachingHe: 'TeachingHE',
    Positions: 'Positions',
    Others: 'Others'
} as const;
export type ProfessionalExperienceDTOTypeEnum = typeof ProfessionalExperienceDTOTypeEnum[keyof typeof ProfessionalExperienceDTOTypeEnum];


/**
 * Check if a given object implements the ProfessionalExperienceDTO interface.
 */
export function instanceOfProfessionalExperienceDTO(value: object): value is ProfessionalExperienceDTO {
    if (!('institution' in value) || value['institution'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ProfessionalExperienceDTOFromJSON(json: any): ProfessionalExperienceDTO {
    return ProfessionalExperienceDTOFromJSONTyped(json, false);
}

export function ProfessionalExperienceDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfessionalExperienceDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'institution': json['institution'],
        'description': json['description'] == null ? undefined : json['description'],
        'startDate': (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'type': json['type'],
        'activities': json['activities'] == null ? undefined : ((json['activities'] as Array<any>).map(ActivityDTOFromJSON)),
    };
}

export function ProfessionalExperienceDTOToJSON(json: any): ProfessionalExperienceDTO {
    return ProfessionalExperienceDTOToJSONTyped(json, false);
}

export function ProfessionalExperienceDTOToJSONTyped(value?: ProfessionalExperienceDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'institution': value['institution'],
        'description': value['description'],
        'startDate': ((value['startDate']).toISOString().substring(0,10)),
        'endDate': value['endDate'] == null ? undefined : ((value['endDate']).toISOString().substring(0,10)),
        'type': value['type'],
        'activities': value['activities'] == null ? undefined : ((value['activities'] as Array<any>).map(ActivityDTOToJSON)),
    };
}

