/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectDTO
 */
export interface ProjectDTO {
    /**
     * 
     * @type {number}
     * @memberof ProjectDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectDTO
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDTO
     */
    institution?: string;
    /**
     * 
     * @type {Date}
     * @memberof ProjectDTO
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProjectDTO
     */
    endDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof ProjectDTO
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDTO
     */
    fundingType: ProjectDTOFundingTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ProjectDTO
     */
    identifier?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDTO
     */
    role?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectDTO
     */
    state?: ProjectDTOStateEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectDTO
     */
    authors: Array<string>;
}


/**
 * @export
 */
export const ProjectDTOFundingTypeEnum = {
    Grant: 'Grant',
    Other: 'Other',
    Contract: 'Contract'
} as const;
export type ProjectDTOFundingTypeEnum = typeof ProjectDTOFundingTypeEnum[keyof typeof ProjectDTOFundingTypeEnum];

/**
 * @export
 */
export const ProjectDTOStateEnum = {
    Concluded: 'Concluded',
    Cancelled: 'Cancelled',
    Ongoing: 'Ongoing'
} as const;
export type ProjectDTOStateEnum = typeof ProjectDTOStateEnum[keyof typeof ProjectDTOStateEnum];


/**
 * Check if a given object implements the ProjectDTO interface.
 */
export function instanceOfProjectDTO(value: object): value is ProjectDTO {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('fundingType' in value) || value['fundingType'] === undefined) return false;
    if (!('authors' in value) || value['authors'] === undefined) return false;
    return true;
}

export function ProjectDTOFromJSON(json: any): ProjectDTO {
    return ProjectDTOFromJSONTyped(json, false);
}

export function ProjectDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'],
        'institution': json['institution'] == null ? undefined : json['institution'],
        'startDate': (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'description': json['description'] == null ? undefined : json['description'],
        'fundingType': json['fundingType'],
        'identifier': json['identifier'] == null ? undefined : json['identifier'],
        'role': json['role'] == null ? undefined : json['role'],
        'state': json['state'] == null ? undefined : json['state'],
        'authors': json['authors'],
    };
}

export function ProjectDTOToJSON(json: any): ProjectDTO {
    return ProjectDTOToJSONTyped(json, false);
}

export function ProjectDTOToJSONTyped(value?: ProjectDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'institution': value['institution'],
        'startDate': ((value['startDate']).toISOString().substring(0,10)),
        'endDate': value['endDate'] == null ? undefined : ((value['endDate']).toISOString().substring(0,10)),
        'description': value['description'],
        'fundingType': value['fundingType'],
        'identifier': value['identifier'],
        'role': value['role'],
        'state': value['state'],
        'authors': value['authors'],
    };
}

