/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SupervisorDTO } from './SupervisorDTO';
import {
    SupervisorDTOFromJSON,
    SupervisorDTOFromJSONTyped,
    SupervisorDTOToJSON,
    SupervisorDTOToJSONTyped,
} from './SupervisorDTO';

/**
 * 
 * @export
 * @interface ThesisDTO
 */
export interface ThesisDTO {
    /**
     * 
     * @type {number}
     * @memberof ThesisDTO
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ThesisDTO
     */
    title: string;
    /**
     * 
     * @type {Array<SupervisorDTO>}
     * @memberof ThesisDTO
     */
    supervisors: Array<SupervisorDTO>;
}

/**
 * Check if a given object implements the ThesisDTO interface.
 */
export function instanceOfThesisDTO(value: object): value is ThesisDTO {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('supervisors' in value) || value['supervisors'] === undefined) return false;
    return true;
}

export function ThesisDTOFromJSON(json: any): ThesisDTO {
    return ThesisDTOFromJSONTyped(json, false);
}

export function ThesisDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThesisDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'],
        'supervisors': ((json['supervisors'] as Array<any>).map(SupervisorDTOFromJSON)),
    };
}

export function ThesisDTOToJSON(json: any): ThesisDTO {
    return ThesisDTOToJSONTyped(json, false);
}

export function ThesisDTOToJSONTyped(value?: ThesisDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'supervisors': ((value['supervisors'] as Array<any>).map(SupervisorDTOToJSON)),
    };
}

